blueprint:
  name: Simple - OffTimerWithTrigger
  description: >
    Aktiviert Entitäten durch Bewegungsmelder (oder andere Trigger) und schaltet sie nach einer definierten Zeit aus.
    Jeder neue Trigger oder manuelles Einschalten setzt den Timer zurück.
  domain: automation

  input:
    target_entities:
      name: Ziel-Entitäten
      description: Entitäten, die eingeschaltet werden und nach der Zeit automatisch ausgehen.
      selector:
        entity:
          domain:
            - light
            - switch
          multiple: true

    trigger_entities:
      name: Trigger-Entitäten
      description: Bewegungsmelder oder andere Trigger (z. B. binary_sensor).
      selector:
        entity:
          domain:
            - binary_sensor
          multiple: true

    delay_minutes:
      name: Ausschaltverzögerung in Minuten
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "min"
          mode: slider

mode: restart

trigger:
  - platform: state
    entity_id: !input trigger_entities
    to: "on"
  - platform: state
    entity_id: !input target_entities
    to: "on"

action:
  - service: homeassistant.turn_on
    target:
      entity_id: !input target_entities

  - delay:
      minutes: !input delay_minutes

  - service: homeassistant.turn_off
    target:
      entity_id: !input target_entities
